[features]
seeds = false

[programs.localnet]
mev_executor = "AtLhxzFGmy6HnzdRrpKHFReVvKWW2CqZWxGE2BEC23x3"

[programs.devnet]
mev_executor = "AtLhxzFGmy6HnzdRrpKHFReVvKWW2CqZWxGE2BEC23x3"

[registry]
url = "https://github.com/coral-xyz/anchor"

[provider]
cluster = "devnet"
wallet = "/home/ybotet/phantom-keypair.json"
